sudo: false
language: python
cache: pip
python:
  - "3.9"
  - "3.10"
  - "3.11"
notifications:
  email: false
# command to install dependencies
install:
  - "pip install --upgrade pip setuptools"
  - "pip install -r requirements.txt"
# command to run nosetests
script: pytest